/**
 * 
 */
package com.graphql_java_generator.gradleplugin;

import java.io.File;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.plugins.JavaPluginConvention;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.compile.JavaCompile;

/**
 * @author EtienneSF
 *
 */
public class GraphqlPlugin implements Plugin<Project> {

	/** The extension name to configure the GraphQL plugin */
	final public static String GRAPHQL_EXTENSION = "graphql";
	/** The name of the task that generates the code from the given GraphQL schemas */
	final public static String GRAPHQL_GENERATE_CODE_TASK_NAME = "graphqlGenerateCode";
	/** The name of SourceSet that contains the code generated by the GraphQL plugin */
	final public static String GRAPHQL_SOURCE_SET_NAME = "graphqlSourceSet";

	@Override
	public void apply(Project project) {
		GraphqlExtension extension = project.getExtensions().create(GRAPHQL_EXTENSION, GraphqlExtension.class, project);
		project.getTasks().register(GRAPHQL_GENERATE_CODE_TASK_NAME, GraphqlGenerateCodeTask.class, project, extension);

		extension.getLog().debug("Applying GraphQL Plugin");

		// Apply the java plugin, then add the generated source
		project.getPlugins().apply(JavaPlugin.class);

		JavaPluginConvention javaConvention = project.getConvention().getPlugin(JavaPluginConvention.class);
		SourceSet main = javaConvention.getSourceSets().getByName(SourceSet.MAIN_SOURCE_SET_NAME);
		main.getJava().srcDir(extension.getTargetSourceFolder());

		// Check of the files added into the compileJava task
		for (File f : ((JavaCompile) project.getTasks().getByName("compileJava")).getSource()) {
			extension.getLog().debug("[After adding GraphQL sources] javaCompile contains: " + f.getAbsolutePath());
		}

	}

}
